ai:
  provider: "ollama"
  model: "qwen3.5:latest" 
  api_key: "http://localhost:11434"
  context_size: 8192
#  provider: "openai" # o "anthropic", "ollama"
#  model: "gpt-4o"
#  api_key: "sk-..."

mcp_servers:
  shell-mcp:
    command: "/Users/marcus.oblak/go/src/github.com/mrqzzz/shell-mcp/shell-mcp" 
    args: [] 
#  filesystem:
#    command: "npx"
#    args: ["-y", "@modelcontextprotocol/server-filesystem", "/Users/me/Desktop"]
#  web:
#    command: "docker"
#    args: ["run", "-i", "mcp/brave-search"]
